package com.app.model.enums;

public enum Genre {

    ACTION, ADVENTURE, ANIMATION, BIOGRAPHY, COMEDY, CRIME, DOCUMENTARY,
    DRAMA, FAMILY, FANTASY, HISTORY, HORROR, MUSIC, MUSICAL, ROMANCE,
    SCI_FI, SPORT, THRILLER, WAR, WESTERN

}
